# AWS \ud658\uacbd\ubcc0\uc218\ub97c OS\uc5d0 \ub4f1\ub85d\ud574 \ub450\uc5c8\ub2e4\uba74 \uc544\ub798 \uadf8\ub300\ub85c \uc0ac\uc6a9 \uac00\ub2a5
# \uc9c1\uc811 \uc785\ub825\ud560 \uacbd\uc6b0 \uc2e4\uc81c \ud0a4 \uac12\uc73c\ub85c \uad50\uccb4 (\uc608: cloud.aws.credentials.access-key=AKIA...)
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

cloud.aws.s3.bucket=oti-s3-kdy
cloud.aws.region=ap-northeast-2